### PR TITLE
Pdf rtl option

### PR DESCRIPTION
**Pull request by vador**
I made a small PR to add the right-to-left option in save_pdf, to allow for duplex printing.
For the moment, I use a separate rb to collate a ltr and a rtl pdf to make duplex pdf :)

Would it be appropriate to add a member "back" to the deck for a more automated procedure ?

I'm not profficient in ruby, so review/criticism is welcome.

### CODE REVIEW

**Comment by vador** [comment]
I modified the log for _save_pdf sample as I use the existing file to add a new save.

**Comment by vador** [comment]
I also changed the base for the PR as you say in the contributing file that it should be update against this branch (but dev is behind master ...)

**Comment by andymeneely** [comment]
This is awesome! Thank you for the contribution. I'll be testing this out soon. At first glance I'm not seeing any glaring issues, assuming it works. You approached it the way I would have.

Be sure to update the CHANGELOG.md with these two features and credit yourself. 

Sorry about the dev behind master. Either one is fine really at the moment.

**Comment by vador** [comment]
done :) Thanks for your work, this is fantastic !

**Comment by vador** [comment]
Hello, trying to print, I seem to have a small offset between front and back sides (a few pixels). 
I need to test with a different printer to know if its the printer or a bug ...

**Comment by andymeneely** [comment]
Merged! Thanks again. Sorry my merge took so long.

**Comment by andymeneely** [comment]
Oh and in response to your comment on slightly different offsets on duplex printing - the new sprues feature might be of help for that.

**Pull request closed without merging**
