### PR TITLE
Preset card size methods and groundwork for better n-up support

### PR DESCRIPTION
**Pull request by andjd**
This update lays the groundwork for creating useful defaults for the save_sheet method and provide better n-up support.

It adds a set convenience methods creating decks of preset standard card sizes.  For example, Squib::Deck.poker will create a new deck of poker-size cards.  Additional arguments sent to the method will be passed through to Squib::Deck.new. A vendor argument can also be passed to these methods, which will set additional attributes of the deck to match the requirements of the vendor profile, such as bleed (more below) and dpi.

This method is implemented using the method_missing technique and looks for card sizes and vendor profiles in YAML files in the new lib/squib/vendor directory.  Eventually, I would also like to have these methods look at files in the project directory as well so users can define custom card sizes.

This update also adds some new attributes of deck, most notably bleed.  When specified, the bleed is added to the width and height attributes.  Trim values in the save methods are also set to the bleed by default.  Other additional attributes are card_name and vendor which are set when the new convenience methods are used. 

These changes present useful functionality as-is, and will be important for implementing the better n-up support settings I plan to implement next.

None of these changes impact backwards compatibility.  This update also contains some housekeeping changes I came across when becoming accustomed to the codebase, such as updating deprecated methods, using "require_relative" instead of "require" when appropriate, and fixing typos in the documentation.

All the tests pass except some of the sample_regression ones, which I don't think represent any problems, but I don't feel confident enough with the code to be 100% sure of that.  My manual testing did not present any issues.

Let me know if you have any questions regarding these changes.

### CODE REVIEW

**Comment by andymeneely** [comment]
Ok, I need to take some time to go over this. But at first glance:
 * I would rather use `require` instead of `require_relative`. If you couldn't get your code to run then you need to do `rake install` to install the gem locally and then run your code. If you create a `foo.rb` file the samples directory and do `rake run[foo]` it will install your new code and run that sample.
  * I'm not sure I'm on board with the `method_missing` approach. Too heavy-handed of a design decision.
  * The `save_9up` method should use the args classes like the others so we have a consistent design.
  * Need a series of samples demonstrating the new features
  * Don't need the byebug file
  * Need spec for the new args class

**Comment by andymeneely** [comment]
For traceability, this is related to #126

**Comment by andjd** [comment]
I thought I had taken out the save_9up method from this pull request.  It's not functional yet.
I'm good creating the samples and specs and removing the byebug file.

As for require vs. require_relative, current best practices are to use require for external libraries and require_relative for internal files.  One of the reasons is that you can't load files out of the load path with require for security reasons. Using require_relative allows the code to operate even if not installed as a gem.  Is there a technical reason you prefer to use require? 

The choice to use method_missing was driven by the desire to have a set of methods that reflect a specification file without having to write a method for each item.  There are alternatives (such as using define_method in a loop) but they would require extra overhead every time the program is run.  The way I have implemented it, the default behavior is maintained unless a valid card type is found in the file, so the technique is not disruptive.  I do believe it's the best option here, and has been implemented in a robust and responsible way.

**Comment by andymeneely** [comment]
For the require_relative discussion - that should really be a separate issue anyway. Let's continue that at #130. 

I'm writing up my thoughts and alternatives for the other stuff.

**Comment by andymeneely** [comment]
Ok, the other stuff. There are a bunch of issues I see here:
  * I don't like adding `bleed` to `Squib::Deck`. That's a slippery slope. A `bleed` is something that only `save_*` methods really need, but now that's one more thing that `Deck` has to keep track of.
  * Specifying default sets of arguments already exists - layouts. As I suggested in #126, I feel like it's more consistent to simply have the `save` methods lookup from layouts.
  * I love meta-programming in Ruby. I do. But I also know myself and I know that I'm less likely to maintain meta-programming code.
  * Errors from method_missing are non-obvious to Ruby newbies (most of Squib's users).
  * We don't need the list of built-in vendor yaml files to be dynamic. If we support more built-in vendor files, we just cut a new release of Squib. If a user wants to define their own yaml files, that's just the layout functionality again and that's fine.

Here's my alternative.

As I suggested in #126, `save_` methods should respect layouts, and then we provide a layout file that defines the `margin`, `gap`, `trim_radius` etc. that we need. If we can't reproduce those templates with `save_sheet`, then we give save_sheet more powers so that it does.

We could also provide convenience methods defined like `save_pnp_productions` that would use those layouts automatically. These would pretty much be wrappers to `save_sheet`.

I am also toying with the idea of letting people set arbitrary defaults programmatically anyway. Order of precedence regarding layouts would have to be figured out, but the general idea would be something like this:

```ruby
Squib::Deck.new do
  default trim: '0.25in'

  save_png prefix: "finished_"       # trim is now 0.25in instead of 0
  save_sheet                         # trim is now 0.25in instead of 0
  save_png prefix: "full_", trim: 0  # trim is 0
end
```

What do you think of those alternatives?

On a process note, I do really appreciate what you're doing here. But I also wish that we had talked some more about it on #126 before forging ahead.

**Comment by andjd** [comment]
Diving into the code base and implementing some changes was the best way for me to see what is actually going on in Squib and see what's reasonably possible to achieve.  I'm more than happy to revisit and reimplement any of the code I've written—and I apologize if I've made you uncomfortable.

regarding presets:
I can fairly easily re-implement my `method_missing` code as `Squib::Deck.preset card: , vendor: nil, **args, &block`  It would then lookup card and vendor arguments in the files as with the current implementation. That keeps all the key functionality without any of the concerns regarding metaprogramming.

regarding `bleed`:
Bleed makes sense to me being a parameter of deck—to me it's conceptually tied to other "immutable" properties like height, width, and dpi.  As i've implemented it, in addition to being used in the save_* methods, it saves you a little bit of math by adding the bleed to the width and height of the deck (which is especially handy because you can't just do `Squib::Deck.new height: '3.5in' + 2 * '.125in', width: ...`).  With the way the code is written, you have to factor in the bleed when you set the height and width, so it makes sense to me that you would set that value right then and there when your thinking about it and not in a different method after you've written all the other methods for the deck or in an entirely separate file.  
Eventually, I'd also like to make it more useful by optionally offsetting the origin of cards by `bleed` in x and y.  This would make it easy to change the size of the bleed without having to re-calculate the x and y of every element on the card. 
I know that personally, I usually start a project with height and width equaling the cut size of the card, and I expect this is typical.
I understand why you don't want to overload the Squib:Deck.new method down with too many arguments, but I think there are good reasons to make `bleed` an exception to this.

regarding `layouts`:
I see what you're getting at with the layouts idea now.  Programmatically, they're just option hashes, but idiomatically, they're about putting stuff on the cards, so I didn't think to use them for defining the save sheet arguments.  I will add that layouts come across as advanced functionality, and aren't the easiest thing for newbies to grasp—the relationship between YAML syntax and ruby objects is non-obvious, especially when combined with your custom `extends` logic.  For that reason, I don't want users to feel that they have to use layouts to access the functionality I'm trying to add.

As far as the `save_sheet` method goes, I will probably augment the save_sheet method for print and play options and write a separate method for saving files that match vendor templates.  To be pixel-perfect, the latter cannot presume even margins and gaps, so such a method will have to micro-manage the render process more than the regular save_sheet.  I will probably do something similar to what I did for the card sizes and look in a directory for a file that has the schematic as opposed to looking in the layout hash.  That way, users won't have to add a `vendor/sheet_layouts/:vendor_name/:card_name` layout file to their deck when they initialize it.

**Comment by andymeneely** [comment]
The yaml layouts are a huge part of what makes Squib useful. If you haven't figured them out already, then I recommend spending time figuring them out. Especially `extends` and ` += ` and `-=` constructs where you can base things off of bleed right in the yaml. 

If layouts could be conveyed more clearly, then let's improve the documentation. That is a big need for Squib - no argument there.

With bleed, I agree that it does make changing the bleed easier later on. But how often is that a big problem? Most of the time when I'm prototyping a game, I just pick a template and go with it. In the rare event that I would switch from one template to another, I have some numbers to change but that's not laborious at all. (Especially if I've leveraged `extends` properly in my layout files.) The words `width` and `height` should mean exactly that - the width and height of the image you're saving to. Making the user know how Squib factors bleed into that is not intuitive to me.

I also don't like the idea of changing the coordinate system to factor in the bleed area. (Technically, you could probably do that already by just calling a cairo `translate`, but I haven't tried that). I don't see how that actually saves people time in the long run.

You could also define a variable. Like this:

```ruby
Squib::Deck.new do
  bleed = 37.5
  text x: bleed + 10
end
```
But again, I like to keep my x's and y's in layout files.

As for saving for vendors:
Let's be more iterative about this. In the publishers branch, I'm just trying to implement saving to the PNP Productions template, which means bringing in some new options to save_sheet like rotate and margin_[north|south|east|west]. 

If it can't be generalized to just a wrapper around save_sheet, then we can do another approach where we define specific pixel locations for specific vendors (e.g. "card 1 is at 152, 237 and rotated clockwise")

Once we have a few vendors written and thoroughly tested, let's *then* refactor the code and make it more general.

**Comment by andjd** [comment]
I'm good with trying to get a more robust save_sheet method working for the vendor templates.  When thinking about it, I've had the irregular pnp productions mini card template in my head (https://www.dropbox.com/sh/x1gdmngwzmko0sp/AACiYrrsGrk3dhInA7qTKX4Da?dl=0) , but that's a special edge case and we should worry about that when we get to it.

I see the height and the width of a card as being the final cut size, but I accept that we'll agree to differ on that fact.  It would be my preference to keep the bleed parameter because I believe it would enable some powerful and useful features more simply than any of the alternatives you've suggested.  Additionally, it would embrace the Ruby Tim Tuesday mentality.  I have been careful that adding the bleed option does not break any existing workflow, but is there for those who will find it helpful.

I'm willing to drop the bleed parameter if you're dead set against it.  I believe I can calculate it when necessary, as is the case when a vendor template uses a different bleed than the bleed used on the deck.

I would like to refactor and just push my changes to add the card/vendor preset size deck creators along the lines of:
```ruby
Squib::Deck.new_preset (card_name: ,vendor: nil, bleed: :none,  **args)
```
If bleed is passed, it will just be added to height and width before being passed to the `Squib::Deck.new` method.  Similar with vendor—it will extend the default size by the vendor's bleed.  The bleed arguments can be passed as `:none`, `:standard` or a value that goes through the unit converter.  Standard will be set to 0.125in.

Does this work for you?

**Comment by andjd** [comment]
I'm closing this pull request and reopening a new one that is smaller in scope.

**Pull request closed without merging**
