### PR TITLE
Default templates for TheGameCrafter [WIP]

### PR DESCRIPTION
**Pull request by sparr**
This PR only contains a draft of the rectangular, circular, and hex templates. The others exist but are mostly empty.

I am seeking feedback on the approach here, before I put in time on the complex cut/safe lines on other templates.

The squib script generated to test this PR depends on #213 and #215, although it can be tested with a more verbose script that doesn't use `draw_layouts` or `layout[]['deck']`.

### CODE REVIEW

**Comment by andymeneely** [comment]
I'd like to bring in all this great work - but I'm thinking I'll go with refining the #219 approach I proposed. So that would mean all of these files won't have the deck stats in them, but then they would go into presets. And the layout feature would remain the same. 

Are you able to work on this in the coming weeks? I finally have some bandwidth for Squib stuff.

**Comment by sparr** [comment]
I've not been working on much outside of work lately, but I did recently find some time to start playing Screeps again so I might also end up with some time for Squib. I can't promise, though, so please don't make plans contingent on my contribution.

**Comment by andymeneely** [comment]
Of course! Thanks for letting me know.

**Comment by andymeneely** [comment]
I'm gonna merge these in and then make some tweaks. Thanks again!!

**Comment by andymeneely** [comment]
Actually, I changed my mind. I'm not quite ready to add 3 megs to the gem size for this. I'll reverting this and we can think about maybe a separate gem, or hitting TGC's api directly or something.

**Comment by andymeneely** [comment]
Oh I just thought of how I could still be helpful with this... a `safe_lines` and `cut_lines` method that is just an alias for `rect` for the standard bleed settings on TGC. I'll put that in.

**Comment by sparr** [comment]
I don't remember all the work I did here, but I have to wonder if the templates on their own would be useful without the images? Also, I may not have crushed the images.

**Comment by andymeneely** [comment]
Actually I don't this included images - it's just 3 megs of yaml! But since most of the files were just the original stats and then cut lines and safe lines. So instead of repeating that data over and over, I just added two method to do it. Here's what they look like: 2362e189d7b786df3dbfabe03ab22ddc1ad571b2

When I think about it, creating deck presets doesn't really save you a ton of time. You usually know the dimensions of your components anyway. I'd rather focus on things that speed up prototyping like front-to-back workflows, bw+color workflows, internationalization, etc.

**Pull request merged**
