### PR TITLE
Fully customizable PDF template sheets

### PR DESCRIPTION
**Pull request by felixleong**
This implements the functionality of #217 Custom save_sheet/save_pdf templates

### CODE REVIEW

**Comment by felixleong** [comment]
Sorry for the long silence, life kind of got in the way.

I finally got around to add some simple examples and some semblance of a unit test in the code base at the moment. Think it could use more test, but it should cover most bases.

Have fixed a couple of bugs that are in the code as well, do review the pull request if you got the time :).

**Comment by andymeneely** [comment]
Definitely. Good timing - my semester has wrapped up and I'll finally have some Squib time this week.

**Comment by andymeneely** [comment]
Ok I'm (finally) gonna do some development on this. I'm gonna adapt a lot of your code, but it won't be a direct merge. 

I can't wait for this feature.

**Comment by andymeneely** [comment]
Alright, this is all in the code base, but called "sprues". I'll be getting this out to beta testers soon. Thanks!!

**Pull request closed without merging**
